version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=master
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres:
